# Generated by Django 5.1.2 on 2024-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_patient_wellnesstransaction_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WellnessTransaction',
            new_name='wellness',
        ),
    ]
